### ISSUE TITLE
what could cause this ?

### ISSUE THREAD

**Issue by Thesourcer1** [BoldGrid/weforms#10]
Hi weforms

i have come across an issue, i don't know if you can help me with. My plugin wont show my entries i've made, and i am only greeted with a popup, that shows me some code to one of my entries, and i don't know how to access it or fix it. 

do you guys have an idea?

Greetings
,Sara

**Comment by tonyr-wv** [comment]
Hi Sara,

We are sorry to hear that you are running into difficulties. If you would be so kind, could you possibly share some steps to reproduce the issue you are seeing as well as some screenshots? That would be immensely helpful in starting to troubleshoot this!

Regards

**Comment by Thesourcer1** [comment]
Hi

Thank you so much for your reply !
i found out that the problem stems from a WordPress update.
I just find it every weird that only a few plugins didn’t Work after the update.
But luckily i had a backup of it all !

Sorry for wasting your time!
Have a great day!

Sara


Fra: tonyr-wv<mailto:notifications@github.com>
Sendt: 5. juni 2020 14:33
Til: BoldGrid/weforms<mailto:weforms@noreply.github.com>
Cc: Thesourcer1<mailto:sara.henriksen95@hotmail.com>; Author<mailto:author@noreply.github.com>
Emne: Re: [BoldGrid/weforms] what could cause this ? (#10)


Hi Sara,

We are sorry to hear that you are running into difficulties. If you would be so kind, could you possibly share some steps to reproduce the issue you are seeing as well as some screenshots? That would be immensely helpful in starting to troubleshoot this!

Regards

**Comment by tonyr-wv** [comment]
Hi Sara,

Glad to hear that the issue was resolved and no need to apologize at all, we are always happy to help whenever possible! 

If anything else pops up that you need assistance with don't hesitate to reach out via here or through support@weformspro.com

Thanks
