### ISSUE TITLE
"Failed to load plugin: code from url https://................/wp-includes/js/tinymce/plugins/code/plugin.min.js"

### ISSUE THREAD

**Issue by ole-code** [BoldGrid/weforms#104]
hi,

when opening or editing a form, this code appears vertically on the left hand side of the page. I can't save changes or create a form and save.

Worpdress v5.7.2

![Screenshot 2021-06-10 180301](https://user-images.githubusercontent.com/85696701/121558663-25f77e00-ca16-11eb-9eeb-c6d6f3e06a4c.png)

**Comment by avonville** [comment]
Resolved in 1.6.9 release.
