### ISSUE TITLE
WP 5.8 - Form editor will not load

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/weforms#106]
I cannot get the form editor to load in either PHP7 or PHP8 environments.

PHP7  FF console error:
![php7](https://user-images.githubusercontent.com/20601160/122973732-8d3ef780-d35f-11eb-9522-67e36fb8ecd5.PNG)

PHP8  FF console error: 
![php8](https://user-images.githubusercontent.com/20601160/122973738-8fa15180-d35f-11eb-90e1-35f6a7d53f25.PNG)

**Comment by avonville** [comment]
On beta3 i get the following:
![image](https://user-images.githubusercontent.com/25781560/123304135-cdc38000-d4db-11eb-940d-105caad25e87.png)
 
 I dont know if this a issue with weforms yet based on the consol information

**Comment by nicolepaschen** [comment]
Beta 4 fixed this issue!
