### ISSUE TITLE
GOogle Sheets Authentication Not working

### ISSUE THREAD

**Issue by shynes** [BoldGrid/weforms#115]
When I try to authorize Google after getting the code to Allow google sheets I get a REd BOx error 
https://share.getcloudapp.com/BluKzYkk

I chose the Correct Gmail account that I am logged into when doing it. INspect shows
https://share.getcloudapp.com/Wnux6BQJ

**Comment by elanasparkle** [comment]
Hello @shynes, 

It is looking like there might be something blocking that from either security on the server or possibly on the site. Are you using any security or potential of using the security in Google?
