### ISSUE TITLE
Reset Form Submissions Count

### ISSUE THREAD

**Issue by elanasparkle** [BoldGrid/weforms#119]
Able to reset the counter of a new form
=========================================================
Name           |   Reset Entry_ID or the count of form submissions
Reporter       |   Elana D.
Submit Date |   8/10/2021
Summary      | Deleting entries and duplicating the form does not reset the Entry_ID counter from a previously used form.

**Comment by avonville** [comment]
Entry_ID is the id for the entries tables. These are all of the entries for all forms. There is no way to reset or have multiple of those ids. One possible solution is to create another column in the entries table that can be the entry counter per form. That would be a feature request/ improvement.

**Comment by elanasparkle** [comment]
@avonville Example is you create a form. Then create a few entries. Then delete all of those entries then the entry_id keeps counting not resetting.

**Comment by avonville** [comment]
Yes that is because the entry id that is displaying is the id for the table not specifically the entry for that form. Changing it would be a massive change to the way the table displays/data is stored

**Comment by avonville** [comment]
This is what it will look like:
![image](https://user-images.githubusercontent.com/25781560/141015719-2fe76359-1447-491e-8995-ae5dc231179a.png)

**Comment by elanasparkle** [comment]
@avonville Isn't it just as easy as saying: 

ALTER TABLE tablename AUTO_INCREMENT = 1

Or if you have to get the current max if there is more than one just looking for the MAX something like: 

SELECT MAX(id) maxid FROM mytable

**Comment by avonville** [comment]
That solution would work if each form had its own entries table. That is not the case here
