### ISSUE TITLE
License Key Notice Persists Despite Adding License Key

### ISSUE THREAD

**Issue by tonyr-wv** [BoldGrid/weforms#135]
Upon installing the premium plugin (personal thru developer), you receive a notice on the dashboard to "Please **enter** your weForms Pro plugin license key to get regular updates and support". Clicking the hyperlink on "enter" you are taken to the license page where you enter your email and license key.

Enter a valid license key and email. You receive a success message  "Your license will expire in 12 month (date is shown)" but the "Please **enter** your weForms Pro plugin license key to get regular updates and support" notice remains. It should not be shown when a valid license and email was entered.

**Comment by avonville** [comment]
@tonyr-wv when you refreshed the page did the notice go away? Just trying to pinpoint where the issue is occurring.

**Comment by avonville** [comment]
https://github.com/BoldGrid/weforms-pro/pull/79
