### ISSUE TITLE
WP5.9 - form doesn't show WYSIWYG in WP Editor

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/weforms#150]
I am using WP 5.9 and 2022 theme. The form doesn't render in the editor like it does in WP5.8 / 2021

![weform-doesnt-show-in-editor](https://user-images.githubusercontent.com/20601160/150838987-62bec47e-4494-41ea-a5cd-2b0c9036aa30.gif)

**Comment by nicolepaschen** [comment]
![image](https://user-images.githubusercontent.com/20601160/150844581-9bebaf92-0baf-4002-863d-624bc6dcad63.png)

**Comment by avonville** [comment]
@nicolepaschen you were able to confirm this is only happening on 2022 WP theme right?

**Comment by nicolepaschen** [comment]
Only 2022 yes - 2021 and Crio display the form both in the PPB and WP Editor
