### ISSUE TITLE
EMAIL NOTIFICATION 

### ISSUE THREAD

**Issue by RUWAN-MAX** [BoldGrid/weforms#23]
HI

I have changed notification email address but sill I am getting emails for WordPress admin email address.
![Screenshot (47)](https://user-images.githubusercontent.com/69752955/90332822-efed9700-dfc8-11ea-8fee-e581e0310a80.png)

**Comment by elanasparkle** [comment]
Hello @RUWAN-MAX 

Thank you for contacting support! What is the notification that you are receiving from the WordPress admin? Can you share the email output? 

Thanks
Elana D.
