### ISSUE TITLE
Columns field doesn't work

### ISSUE THREAD

**Issue by andyekim** [BoldGrid/weforms#28]
"Columns" field doesn't make divided sections 

There I see this css unit

ul.wpuf-form .wpuf-field-columns.has-columns-2 .wpuf-column .wpuf-column-inner-fields {
     width: 50% !important;
     float: left;
}

but this element style persists

element.style {
    width: 365%;
}

Please see the link below.
http://104.244.124.6/~kasecc5/?page_id=6040

Thank you

**Comment by elanasparkle** [comment]
Hello @andyekim 

Thanks for that i did some testing and I'm not sure why you're style is that way without being able to see more but i tested the columns and was able to set them to 50% but you should see something like. 

/* This rule makes the DOB field to 50% */
.items-of-column-2.wpuf-column-inner-fields {
	width: 50% !important;
}

Thanks
Elana D.
