### ISSUE TITLE
Excessive admin notices

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/weforms#35]
Feels like a little too much:

![image](https://user-images.githubusercontent.com/5925563/96591750-96019a00-12b5-11eb-8cc0-96e561391f88.png)

**Comment by bwmarkle** [comment]
@cssjoe doesn't like this either
![image](https://user-images.githubusercontent.com/5925563/99411879-15d55100-28c2-11eb-81f0-395fede9f774.png)

**Comment by bwmarkle** [comment]
It takes over w3tc too
![image](https://user-images.githubusercontent.com/5925563/99552687-4a610f80-298b-11eb-9e64-363372cf8dee.png)

**Comment by bwmarkle** [comment]
@cssjoe doesn't like this either 
![image](https://user-images.githubusercontent.com/5925563/99723179-d3f20980-2a7f-11eb-872a-6120e953e2fc.png)

**Comment by bwmarkle** [comment]
@jamesros161 is working on it!

**Comment by bwmarkle** [comment]
@jamesros161 this ticket is completed, yeah?

**Comment by elanasparkle** [comment]
Resolved with Version 1.3.13 and Version 1.6.5
