### ISSUE TITLE
You are running Vue in development mode.

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/weforms#38]
Not 100%, but looks like we're running vue in dev mode.

https://vuejs.org/v2/guide/deployment.html
> During development, Vue provides a lot of warnings to help you with common errors and pitfalls. However, these warning strings become useless in production and bloat your app’s payload size. In addition, some of these warning checks have small runtime costs that can be avoided in production mode.

![image](https://user-images.githubusercontent.com/5925563/98369670-4c2fe800-2007-11eb-9cac-0a00c741bf09.png)

**Comment by harryjackson1221** [comment]
https://github.com/BoldGrid/weforms/blob/9a8f9db1bbc7695be24ab5cc62abc475cd3b6201/assets/wpuf/vendor/vue/vue.js#L7192
