### ISSUE TITLE
SMS Notifications with SMS Global Not Sending Properly Due to Legacy APIs

### ISSUE THREAD

**Issue by stevenll88** [BoldGrid/weforms#40]
=========================================================
Name | SMS Notifications with SMS Global Not Sending Properly Due to Legacy APIs
Reporter | Steven Ll. 
Submit Date | 11/12/2020
Summary | 
Email from SMS Global:
"I raised the issue with our tech team and looks like weForms is using our legacy APIs.
They need to be connecting to https://api.smsglobal.com/http-api.php
Full API URL sample - https://api.smsglobal.com/http-api.php?action=sendsms&user=(USERNAME)&password=(PASSWORD)&from=(CUSTOMWORD)&to=(NUMBER)&text=(MESSAGE)"
Platform | weForms
PHP Version | n/a
Browser | n/a

More information to be collected.

**Comment by stevenll88** [comment]
More notes regarding above issue:

Customer is using:

- Nginx Server
- PHP: 7.4
- WP: 5.5.3
- The latest weforms - 1.6.3
- Latest weforms pro 1.3.11

It's not sending an sms at all with globalsms. There aren't any error messages in wordpress. Symptoms: no sms sent, no error messages. When talking to smsglobal, there was nothing being recorded in globalsms dashboard logs. This prompted their team to look into it and came to the conclusion that an old api address is being called.

**Comment by elanasparkle** [comment]
Resolved with Version 1.3.13 and Version 1.6.5
