### ISSUE TITLE
Conditional Logic not working

### ISSUE THREAD

**Issue by LordCanon** [BoldGrid/weforms#47]
https://secure.helpscout.net/conversation/1370364691/2603?folderId=3464808

Name           |   Conditional logic issues 
Reporter       |   Elana D.
Submit Date |    9/9/2020
Summary      | When two fields are added and set up to use conditional logic, both fields show the entire time regardless of logic |
Platform       | WP 5.6 / WeForms Pro 1.3.12

**Comment by elanasparkle** [comment]
Resolved in weForms1.6.6 & 1.3.14
