### ISSUE TITLE
[Bug] Twilio SMS Feature not working

### ISSUE THREAD

**Issue by harryjackson1221** [BoldGrid/weforms#48]
Setting up Twilio for SMS notifications is not working, enabling WP Debug shows the following:

![image](https://user-images.githubusercontent.com/29436971/102830560-8dae0400-43b7-11eb-969a-4b6ef13067eb.png)

Deprecated: Function create_function() is deprecated in /home/cfcloudwp/public_html/wp-content/plugins/weforms-developer/modules/sms-notification/vendor/twilio/sdk/Services/Twilio/Resource.php on line 93

PHP v7.4
CENTOS 7.9

**Comment by elanasparkle** [comment]
Resolved with Version 1.3.13 and Version 1.6.5
