### ISSUE TITLE
Right Side Bar Disappeared on the Form Editor - I cant make a form anymore

### ISSUE THREAD

**Issue by alid0n** [BoldGrid/weforms#52]
I was creating a form and the sidebar with the fields and field data just went blank, I cant do anything now. Even after refreshing the page and closing the entire thing and re opening it its still gone. Not sure what to do.

**Comment by harryjackson1221** [comment]
Hello [@alid0n](https://github.com/alid0n)

Thank you for reaching out!

Sorry to hear you are having issues with your weForms plugin and using the builder. Are you using the free or pro version? What version are the plugins on, and what version of WordPress are you currently on? We have not seen this issue on any of our testing environments currently, but we would be glad to do what we can to help figure it out.

**Comment by alid0n** [comment]
I am using the pro version.

 I just bought it yesterday. Would I be able to get a refund? It doesnt
have a few features I was hoping for and Ive decided I dont need it.

Thank you for your time.

**Comment by elanasparkle** [comment]
Hello @alid0n 

Sure, if you wanted to reach out to support from the chat icon on the https://weformspro.com/ page with all of your payment information, we can look into that for you. 

Thanks
Elana D.
