### ISSUE TITLE
Blank fields When Zoomed

### ISSUE THREAD

**Issue by elanasparkle** [BoldGrid/weforms#59]
Setting zoom to every other section the fields disappear. IE: set browser zoom to 75% and weForms fields disappear. 

![image](https://user-images.githubusercontent.com/5271694/111002698-e1dfd900-8353-11eb-9b49-121d1d6b464b.png)

**Comment by avonville** [comment]
This when Zoomed out, I was not able to replicate the issue when zoomed in to over 150%. The issue looks to only happen at less than 75%. The file it is calling is a core Wordpress tinymce.min.js in wp-includes.

**Comment by avonville** [comment]
Removing from 1.6.10 for now unless this is affecting many users. Looks like it is only affecting certain zoom percentages below 75%
