### ISSUE TITLE
[Bug] Show Report on Frontend does not work

### ISSUE THREAD

**Issue by joe9663** [BoldGrid/weforms#98]
**Description**
Enabling the Show Report on Frontend does not display form data after completing submission.

Error in Console:
`jquery.min.js?ver=3.5.1:2 Uncaught TypeError: Cannot read property 'getContext' of null`
   `at new o (signature_pad.min.js?ver=1.6.6:1)`
   `at HTMLDocument.<anonymous> (signature-field.js?ver=1.6.6:3)`
   `at e (jquery.min.js?ver=3.5.1:2)`
   `at t (jquery.min.js?ver=3.5.1:2)`

**Replication**
1. Enable Show Report on Frontend under Form Settings
2. Submit form content
3. See error

[Form used for testing](https://cf.cloudwp.dev/weforms/file-uploads/)

**Environment Details**
- WordPress 5.7.2
- PHP 7.4.19
- weForms 1.6.6
- weForms Pro Developer 1.3.14

**Comment by avonville** [comment]
This has been fixed with the most recent release.
